# Contributor Metrics

## Item Counts
the number of agents includes those how have only starred the repo - the number of actual active agents is 42

In [1]:
from kieker_analysis.queries.queries import QueryOld
from kieker_analysis.sparql.client import run_dataframe, kieker_client, keiker_ii_client

run_dataframe(QueryOld.counts, client=keiker_ii_client)

   agents  pullreqs  issues  commits  comments  reviews  r_reqs
0     149       742    2902     9131      6257      176     152

# User Activity
Here we look at user activity in terms of the metrics used in the Cheng Paper.
Note that ```closed_pull```, ```mention_issue_comments```, ```mention_pull_comments```, ```referred_issue_comments``` are constant and are all zero.
```closed_issue```, ```labels_pull```, ``` issues_opened```, ```labels_issue``` are all by one user ```rju``` or by them with one or two by ```DaGeRe```. These variables don't have enough values to be useful

In [1]:
from kieker_analysis.stats.contributor_metrics_old import get_user_activity, metrics_all
client = kieker_client
metrics_all = metrics_all(client)
user_activity = get_user_activity(metrics_all)
user_activity

NameError: name 'kieker_client' is not defined

In [2]:
from kieker_analysis.stats.contributor_metrics_old import get_user_activity, metrics_all
client = keiker_ii_client
metrics_all = metrics_all(client)
user_activity = get_user_activity(metrics_all)
user_activity

NameError: name 'keiker_ii_client' is not defined

The user activities and counts present in Kieker are shown below, along with the number of associated agents.

In [1]:
from kieker_analysis.stats.contributor_metrics_old import get_kieker_event_count
get_kieker_event_count()

                                           event_type  events  agents
1                 http://purl.org/github2prov/comment    6257      21
2                http://purl.org/github2prov/assigned    1027       7
3                 http://purl.org/github2prov/labeled    2105       3
4                  http://purl.org/github2prov/closed    2204      17
5              http://purl.org/github2prov/unassigned       4       1
6               http://purl.org/github2prov/connected       2       1
7                 http://purl.org/github2prov/renamed       7       6
8                http://purl.org/github2prov/reopened      34       6
9        http://purl.org/github2prov/head_ref_deleted     538      14
10      http://purl.org/github2prov/head_ref_restored      13       5
11  http://purl.org/github2prov/review_request_rem...       8       2
12  http://purl.org/github2prov/head_ref_force_pushed     445       4
13    http://purl.org/github2prov/pull_request_review     176       8
14             http://purl.org/github2prov/referenced       5       3
15                 http://purl.org/github2prov/merged     619      10
16       http://purl.org/github2prov/base_ref_changed      21       9
17       http://purl.org/github2prov/review_requested     152       7
18    http://purl.org/github2prov/marked_as_duplicate       1       1
19       http://purl.org/github2prov/review_dismissed      27       3
20              http://purl.org/github2prov/unlabeled       5       1
21           http://purl.org/github2prov/unsubscribed       1       1

The results are possibly skewed by certain users. Let's try dropping a few...

In [2]:
dropped_users=['users:rju']
get_kieker_event_count(dropped_users)

                                           event_type  events  agents
1              http://purl.org/github2prov/unassigned       4       1
2                  http://purl.org/github2prov/closed     382      16
3                 http://purl.org/github2prov/comment     195      20
4               http://purl.org/github2prov/connected       2       1
5                 http://purl.org/github2prov/renamed       7       6
6        http://purl.org/github2prov/head_ref_deleted     354      13
7       http://purl.org/github2prov/head_ref_restored       6       4
8   http://purl.org/github2prov/review_request_rem...       8       2
9   http://purl.org/github2prov/head_ref_force_pushed     445       4
10                http://purl.org/github2prov/labeled     400       2
11             http://purl.org/github2prov/referenced       5       3
12               http://purl.org/github2prov/assigned      13       6
13               http://purl.org/github2prov/reopened      18       5
14       http://purl.org/github2prov/base_ref_changed      17       8
15                 http://purl.org/github2prov/merged     258       9
16       http://purl.org/github2prov/review_requested      82       6
17    http://purl.org/github2prov/pull_request_review     110       7
18    http://purl.org/github2prov/marked_as_duplicate       1       1
19              http://purl.org/github2prov/unlabeled       5       1
20       http://purl.org/github2prov/review_dismissed      12       2
21           http://purl.org/github2prov/unsubscribed       1       1

Still the same number of events, Many of these are not present in the values used in the analysis in Cheng, and the Analysis.ipnb. Most seem to bave better looking distributions. Let's see what they look like for all users...

In [1]:
from kieker_analysis.stats.contributor_metrics_old import get_all_user_metrics
get_all_user_metrics()

event_type_short,agent,assigned,base_ref_changed,closed,comment,connected,head_ref_deleted,head_ref_force_pushed,head_ref_restored,labeled,...,pull_request_review,referenced,renamed,reopened,review_dismissed,review_request_removed,review_requested,unassigned,unlabeled,unsubscribed
0,https://github.com/ChristianStier,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,https://github.com/ChristianWulf,2,2,57,15,0,45,0,0,0,...,5,0,1,0,0,0,0,0,0,0
2,https://github.com/Col20s,0,0,3,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,https://github.com/DaGeRe,2,0,145,52,0,43,72,0,0,...,12,0,2,0,10,0,25,0,0,0
4,https://github.com/DanielMSchmidt,0,0,2,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,https://github.com/Marcel-Ha,0,0,0,0,2,0,2,0,0,...,0,0,1,0,0,0,0,0,0,0
6,https://github.com/Rackles,0,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,https://github.com/SoerenHenning,1,2,4,5,0,0,0,0,0,...,18,1,0,0,0,0,3,4,0,0
8,https://github.com/WassimDhib,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,https://github.com/aaschmid,0,2,1,5,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
10,https://github.com/apps/dependabot,0,0,33,37,0,188,369,0,393,...,0,0,0,0,0,0,0,0,0,0
11,https://github.com/avanhoorn,1,2,38,19,0,19,0,1,0,...,31,0,0,2,0,1,5,0,0,0
12,https://github.com/cbkurz,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,https://github.com/czirkelbach,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,https://github.com/duelle,6,1,67,37,0,43,2,3,7,...,26,0,0,5,2,7,42,0,5,0
15,https://github.com/holgerknoche,1,6,4,1,0,0,0,0,0,...,3,0,0,1,0,0,1,0,0,0
16,https://github.com/jan,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,https://github.com/kieker-ci,0,1,15,1,0,3,0,1,0,...,0,0,0,9,0,0,0,0,0,0
18,https://github.com/lbl-dev,0,0,7,0,0,6,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,https://github.com/madcau,0,0,2,1,0,2,0,0,0,...,0,0,0,0,0,0,6,0,0,0
20,https://github.com/malte-hansen,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,https://github.com/marius,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,https://github.com/monperrus,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,https://github.com/nils,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,https://github.com/ole,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,https://github.com/rju,1014,4,1822,6062,0,184,0,7,1705,...,66,0,0,16,15,0,70,0,0,0
26,https://github.com/shinhyungyang,0,0,1,10,0,1,0,0,0,...,15,3,1,0,0,0,0,0,0,0
27,https://github.com/stro18,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,https://github.com/wds8237,0,0,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0

## Issues and Jira
so there is a problem with the way issues are created in Kieker